language: node_js
node_js:
  - '6.10.0'
script:
  - "npm test --coverage"
notifications:
  email: false
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
